### PR TITLE
Update to CFLint and Atom

### PR DESCRIPTION
**Pull request by msp1kpj**
I have update the CFLint Jar and the integration into the atom-linter.

### CODE REVIEW

**Comment by sjmatta** [comment]
I'm no longer with @ditinc and I don't have rights to merge pull requests anymore. @jtl3d, @treyyoder, or @lramirez925 may be able to assist.

**Comment by sjmatta** [comment]
Sorry for the delay. I'm a contributer again and I can take a look now.

**Comment by lramirez925** [comment]
Sorry for lack of response. Between school and work right now I don’t have much time to help out. Especially since I have moved away from using atom. If I get some time maybe I’ll look at other issues

**Comment by sjmatta** [comment]
This works great! Thank you for your contribution.

**Comment by sjmatta** [comment]
I published 0.15.0 with your changes - it should be available immediately.

**Comment by msp1kpj** [comment]
Thanks we appreciate it very much!

**Comment by msp1kpj** [comment]
Just because I like to use any development software I can try. What did you
move to after Atom?

**Comment by sjmatta** [comment]
Personally I'm still on Atom, but I know for some it has performance issues that are insurmountable, especially on older machines.

**Comment by lramirez925** [comment]
@msp1kpj I have started to use Visual Studio Code. I mainly changed back when it had a very nice git compare tool. (Still does) But I have seen that atom has caught up there. I also had some of the performance issues that @sjmatta mentioned and vs code did not give me the same issues.

**Pull request merged**
